### ISSUE TITLE
py.test deprecation warning

### ISSUE THREAD

**Issue by Dowwie** [uber/doubles#101] opened 2015-12-16 16:21 UTC
using py.test 2.8.5:

/doubles/pytest.py:3 'pytest_runtest_call' hook uses deprecated __multicall__ argument

**Comment by lopter** [comment] 2015-12-24 09:31
Duplicate of #98.

**Comment by lopter** [comment] 2015-12-24 09:35
Also straight duplicate of #99.

**Closed by lopter** 2015-12-24 09:35 UTC
Labels: duplicate
